"""
Generate numbers.tex for stupid.tex from real sources.

Sources of truth:
  - ../stu-pid.py (the Config class) for hyperparameters and model name
  - ../results/results_df_optimized.csv for accuracy / token metrics

Run from this directory:
    python build_numbers.py

Writes: numbers.tex (committed alongside stupid.tex so arXiv can compile
without running this script).
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

csv.field_size_limit(sys.maxsize)

HERE = Path(__file__).parent
REPO = HERE.parent
CONFIG_PY = REPO / "stu-pid.py"
RESULTS_CSV = REPO / "results" / "results_df_optimized.csv"
OUT = HERE / "numbers.tex"


# ---------- parse Config class from stu-pid.py ----------

def parse_config(path: Path) -> dict:
    src = path.read_text()
    # grab the "class Config" block
    m = re.search(r"class RASPIDConfig[^:]*:\n(.*?)(?=\nclass |\Z)", src, re.S)
    if not m:
        raise RuntimeError(f"RASPIDConfig class not found in {path}")
    block = m.group(1)

    cfg: dict = {}

    def grab(name: str, pattern: str):
        mm = re.search(pattern, block)
        if not mm:
            raise RuntimeError(f"Could not parse {name} from Config")
        cfg[name] = mm.group(1).strip()

    grab("MODEL_NAME", r'MODEL_NAME\s*=\s*"([^"]+)"')
    grab("EMB_LAYER", r"EMB_LAYER\s*=\s*(\d+)")
    grab("FLUFF_STAR", r"FLUFF_STAR\s*=\s*([\d.eE+-]+)")
    grab("INIT_FREE", r"INIT_FREE\s*=\s*(\d+)")
    grab("STEER_WINDOW", r"STEER_WINDOW\s*=\s*(\d+)")
    grab("MAX_I", r"MAX_I\s*=\s*([\d.eE+-]+)")
    grab("MAX_ALPHA", r"MAX_ALPHA\s*=\s*([\d.eE+-]+)")
    grab("STEER_MARGIN", r"STEER_MARGIN\s*=\s*([\d.eE+-]+)")
    grab("MAX_TOKENS", r"MAX_TOKENS\s*=\s*(\d+)")
    grab("BASE_TEMP", r"BASE_TEMP\s*=\s*([\d.eE+-]+)")
    grab("STEER_TEMP", r"STEER_TEMP\s*=\s*([\d.eE+-]+)")

    # KP, KI, KD on a single line
    mk = re.search(
        r"KP\s*,\s*KI\s*,\s*KD\s*=\s*([\d.eE+-]+)\s*,\s*([\d.eE+-]+)\s*,\s*([\d.eE+-]+)",
        block,
    )
    if not mk:
        raise RuntimeError("Could not parse KP/KI/KD from Config")
    cfg["KP"], cfg["KI"], cfg["KD"] = mk.group(1), mk.group(2), mk.group(3)

    # chunk size: prefer a concrete trained value if there is one, else
    # use the first entry of CHUNK_SIZES as the default
    ms = re.search(r"CHUNK_SIZES\s*=\s*\[([^\]]+)\]", block)
    if not ms:
        raise RuntimeError("Could not parse CHUNK_SIZES from Config")
    chunk_sizes = [int(x) for x in re.findall(r"\d+", ms.group(1))]
    cfg["CHUNK_SIZE_DEFAULT"] = str(max(chunk_sizes))  # 24 is the larger
    cfg["CHUNK_SIZES_LIST"] = ", ".join(str(x) for x in chunk_sizes)

    return cfg


# ---------- parse results CSV ----------

def norm(x: str) -> str | None:
    if x is None:
        return None
    s = str(x).strip().replace(",", "").replace("$", "").replace("\\", "").replace(" ", "")
    if s == "" or s.lower() == "nan":
        return None
    try:
        return str(float(s))
    except ValueError:
        return s.lower()


def load_results(path: Path) -> dict:
    rows = list(csv.DictReader(path.open()))
    n = len(rows)
    if n == 0:
        raise RuntimeError(f"No rows in {path}")

    b_ok = r_ok = 0
    b_tok = r_tok = 0.0
    for row in rows:
        gold = norm(row.get("reference_correct") or "")
        bn = norm(row.get("baseline_correct") or "")
        rn = norm(row.get("raspid_correct") or "")
        if gold is not None:
            if bn == gold:
                b_ok += 1
            if rn == gold:
                r_ok += 1
        b_tok += float(row["baseline_tokens"])
        r_tok += float(row["raspid_tokens"])

    b_acc = 100.0 * b_ok / n
    r_acc = 100.0 * r_ok / n
    b_tok_mean = b_tok / n
    r_tok_mean = r_tok / n

    return {
        "N": n,
        "BASELINE_ACC": f"{b_acc:.1f}",
        "STUPID_ACC": f"{r_acc:.1f}",
        "ACC_DELTA_PP": f"{r_acc - b_acc:.1f}",
        "BASELINE_TOKENS": f"{b_tok_mean:.0f}",
        "STUPID_TOKENS": f"{r_tok_mean:.0f}",
        "TOKEN_REDUCTION_PCT": f"{100.0 * (b_tok_mean - r_tok_mean) / b_tok_mean:.0f}",
    }


# ---------- emit numbers.tex ----------

def fmt_sci(s: str) -> str:
    """Format a float literal for LaTeX math mode, e.g. '0.0005' -> '5\\!\\times\\!10^{-4}'."""
    v = float(s)
    if v == 0:
        return "0"
    if abs(v) >= 1e-3:
        # keep as plain decimal, strip trailing zeros
        return ("%g" % v)
    # scientific
    exp = 0
    mant = v
    while abs(mant) < 1:
        mant *= 10
        exp -= 1
    return f"{mant:g}\\!\\times\\!10^{{{exp}}}"


def main() -> None:
    cfg = parse_config(CONFIG_PY)
    res = load_results(RESULTS_CSV)

    # short model name for the prose
    model_full = cfg["MODEL_NAME"]
    model_short = model_full.split("/")[-1]

    lines = [
        "% Auto-generated by build_numbers.py. Do not edit by hand.",
        "% Sources: ../stu-pid.py (Config), ../results/results_df_optimized.csv",
        "",
        "% --- Model / data ---",
        f"\\newcommand{{\\ModelName}}{{{model_short}}}",
        f"\\newcommand{{\\NProblems}}{{{res['N']}}}",
        "",
        "% --- Results ---",
        f"\\newcommand{{\\BaselineAcc}}{{{res['BASELINE_ACC']}}}",
        f"\\newcommand{{\\StupidAcc}}{{{res['STUPID_ACC']}}}",
        f"\\newcommand{{\\AccDeltaPP}}{{{res['ACC_DELTA_PP']}}}",
        f"\\newcommand{{\\BaselineTokens}}{{{res['BASELINE_TOKENS']}}}",
        f"\\newcommand{{\\StupidTokens}}{{{res['STUPID_TOKENS']}}}",
        f"\\newcommand{{\\TokenReductionPct}}{{{res['TOKEN_REDUCTION_PCT']}}}",
        "",
        "% --- Classifier ---",
        f"\\newcommand{{\\EmbLayer}}{{{cfg['EMB_LAYER']}}}",
        f"\\newcommand{{\\ChunkSize}}{{{cfg['CHUNK_SIZE_DEFAULT']}}}",
        f"\\newcommand{{\\ChunkSizesList}}{{{cfg['CHUNK_SIZES_LIST']}}}",
        "",
        "% --- PID hyperparameters (math-mode formatted) ---",
        f"\\newcommand{{\\KP}}{{{fmt_sci(cfg['KP'])}}}",
        f"\\newcommand{{\\KI}}{{{fmt_sci(cfg['KI'])}}}",
        f"\\newcommand{{\\KD}}{{{fmt_sci(cfg['KD'])}}}",
        f"\\newcommand{{\\PTarget}}{{{fmt_sci(cfg['FLUFF_STAR'])}}}",
        f"\\newcommand{{\\AlphaMax}}{{{fmt_sci(cfg['MAX_ALPHA'])}}}",
        f"\\newcommand{{\\IMax}}{{{fmt_sci(cfg['MAX_I'])}}}",
        f"\\newcommand{{\\SteerMargin}}{{{fmt_sci(cfg['STEER_MARGIN'])}}}",
        "",
        "% --- Control schedule ---",
        f"\\newcommand{{\\InitFree}}{{{cfg['INIT_FREE']}}}",
        f"\\newcommand{{\\SteerWindow}}{{{cfg['STEER_WINDOW']}}}",
        f"\\newcommand{{\\MaxTokens}}{{{cfg['MAX_TOKENS']}}}",
        "",
        "% --- Sampling temperature (coupled to steering strength) ---",
        f"\\newcommand{{\\BaseTemp}}{{{fmt_sci(cfg['BASE_TEMP'])}}}",
        f"\\newcommand{{\\SteerTemp}}{{{fmt_sci(cfg['STEER_TEMP'])}}}",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
